# title: "Ayesha Subhashanee Hallala Hewage"
show_downloads: false
theme: jekyll-theme-minimal

description: |
  <style>
    .profile-container {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      justify-content: center;
      text-align: center;
      padding: 20px;
      max-width: 900px;
      margin: 0 auto;
    }

    .profile-image {
      display: flex;
      justify-content: center;
      margin-bottom: 20px;
    }

    .profile-image img {
      width: 180px;
      height: 180px;
      border-radius: 50%;
      object-fit: cover;
      border: 3px solid #555;
    }

    .profile-details {
      width: 100%;
      max-width: 600px;
      padding: 10px;
    }

    .contact-info {
      display: flex;
      flex-direction: column;
      gap: 10px;
      margin-top: 20px;
    }

    .contact-item {
      display: flex;
      align-items: center;
      gap: 10px;
    }

    .contact-item img {
      width: 20px;
      height: 20px;
    }

    @media (max-width: 600px) {
      .profile-container {
        flex-direction: column;
      }
    }
  </style>

  <div class="profile-container">
    <div class="profile-image">
      <img src="assets/Ayesha-Profilepic.jpg" alt="Ayesha Subhashanee">
    </div>

    <div class="profile-details">
      <h2>Contact</h2>
      <div class="contact-info">
        <div class="contact-item">
          <img src="assets/Email-icon.png" alt="Email Icon">
          <a href="mailto:ayeshasubha700@gmail.com">ayeshasubha700@gmail.com</a>
        </div>
        <div class="contact-item">
          <img src="assets/github-icon.png" alt="GitHub Icon">
          <a href="https://github.com/Ayesha-Subhashanee" target="_blank">github.com/Ayesha-Subhashanee</a>
        </div>
      </div>
    </div>
  </div>
