show_downloads: false
theme: jekyll-theme-minimal

description: |
  <style>
    .profile-container {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 30px;
      text-align: center;
    }
    .profile-image img {
      width: 150px;
      height: 150px;
      border-radius: 50%;
      border: 3px solid #ccc;
    }
    .contact-item {
      display: flex;
      align-items: center;
      gap: 8px;
      font-size: 14px;
    }
    .contact-item img {
      width: 18px;
      height: 18px;
    }
  </style>

  <div class="profile-container">
    <img src="/assets/Ayesha-Profilepic.jpg" class="profile-image" alt="Ayesha Subhashanee">
    <h2>Contact</h2>
    <div class="contact-item">
      <img src="/assets/Email-icon.png" alt="Email">
      <a href="mailto:ayeshasubha700@gmail.com">ayeshasubha700@gmail.com</a>
    </div>
    <div class="contact-item">
      <img src="/assets/github-icon.png" alt="GitHub">
      <a href="https://github.com/Ayesha-Subhashanee">github.com/Ayesha-Subhashanee</a>
    </div>
  </div>
