title: "Ayesha Subhashanee"
logo: /assets/Ayesha-Profilepic.jpg
show_downloads: false
theme: jekyll-theme-minimal

# Contact Information
email: ayeshasubha700@gmail.com
github: Ayesha-Subhashanee

# Customizing the Page Design
description: |
  <style>
    .profile-container {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      justify-content: center;
      text-align: center;
      padding: 20px;
    }
    .profile-image {
      display: flex;
      justify-content: center;
      margin-bottom: 20px;
    }
    .profile-image img {
      width: 25%;
      max-width: 200px;
      min-width: 120px;
      border-radius: 50%;
    }
    .profile-details {
      width: 100%;
      max-width: 600px;
      text-align: left;
    }
    .contact-info {
      display: flex;
      flex-direction: column;
      gap: 10px;
      margin-top: 20px;
    }
    .contact-item {
      display: flex;
      align-items: center;
      gap: 10px;
    }
    .contact-item img {
      width: 20px;
      height: 20px;
    }
    @media (max-width: 600px) {
      .profile-container {
        flex-direction: column;
        text-align: center;
      }
      .profile-details {
        text-align: center;
      }
    }
  </style>

  <div class="profile-container">
    <div class="profile-image">
      <img src="/assets/Ayesha-Profilepic.jpg" alt="Ayesha Subhashanee">
    </div>
    <div class="profile-details">
      <h2>Contact</h2>
      <div class="contact-info">
        <div class="contact-item">
          <img src="/assets/Email-icon.png" alt="Email">
          <a href="mailto:ayeshasubha700@gmail.com">ayeshasubha700@gmail.com</a>
        </div>
        <div class="contact-item">
          <img src="/assets/github-icon.png" alt="GitHub">
          <a href="https://github.com/Ayesha-Subhashanee">github.com/Ayesha-Subhashanee</a>
        </div>
      </div>
    </div>
  </div>
