title: "Ayesha Subhashanee"
logo: "/assets/Ayesha-Profilepic.jpg"
show_downloads: false
theme: jekyll-theme-minimal

# Contact Information
email: "ayeshasubha700@gmail.com"
github: "Ayesha-Subhashanee"

# Customizing the Page Design
description: |
  <style>
    /* Profile Container */
    .profile-container {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 30px;
      text-align: center;
    }

    /* Profile Image */
    .profile-image {
      width: 180px;
      height: 180px;
      border-radius: 50%;
      border: 3px solid #555;
      object-fit: cover;
      margin-bottom: 15px;
    }

    /* Contact Section */
    .contact-info {
      margin-top: 20px;
      font-size: 16px;
      font-weight: 500;
    }

    .contact-item {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 10px;
      margin: 5px 0;
    }

    .contact-item img {
      width: 18px;
      height: 18px;
    }
  </style>

  <div class="profile-container">
    <img src="/assets/Ayesha-Profilepic.jpg" class="profile-image" alt="Ayesha Subhashanee">
    <h2>Contact</h2>
    <div class="contact-info">
      <div class="contact-item">
        <img src="/assets/Email-icon.png" alt="Email">
        <a href="mailto:ayeshasubha700@gmail.com">ayeshasubha700@gmail.com</a>
      </div>
      <div class="contact-item">
        <img src="/assets/github-icon.png" alt="GitHub">
        <a href="https://github.com/Ayesha-Subhashanee">github.com/Ayesha-Subhashanee</a>
      </div>
    </div>
  </div>
