#title: "Radin Dinsara Gunarathne"
show_downloads: false
theme: jekyll-theme-minimal

description: |
  <style>
    .profile-container {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      justify-content: center;
      text-align: center;
      padding: 20px;
    }
    .profile-image {
      display: flex;
      justify-content: center;
      margin-bottom: 20px;
    }
    .profile-image img {
      width: 25%;
      max-width: 200px;
      min-width: 120px;
      border-radius: 50%;
    }
    .profile-details {
      width: 100%;
      max-width: 600px;
      text-align: left;
    }
    .contact-info {
      display: flex;
      flex-direction: column;
      gap: 10px;
      margin-top: 20px;
    }
    .contact-item {
      display: flex;
      align-items: center;
      gap: 10px;
    }
    .contact-item img {
      width: 20px;
      height: 20px;
    }
    @media (max-width: 600px) {
      .profile-container {
        flex-direction: column;
        text-align: center;
      }
      .profile-details {
        text-align: center;
      }
    }
  </style>

  <div class="profile-container">
    <div class="profile-image">
      <img src="/assets/Radin-profile pic.png" alt="Radin Dinsara Gunarathne">
    </div>
    <div class="profile-details">
      <h2>Contact</h2>
      <div class="contact-info">
        <div class="contact-item">
          <img src="/assets/Location-icon.png" alt="Location">
          <span><strong>Gampaha, Sri Lanka</strong></span>
        </div>
        <div class="contact-item">
          <img src="/assets/Email-icon.png" alt="Email">
          <a href="mailto:radinpersonald@gmail.com">radinpersonald@gmail.com</a>
        </div>
        <div class="contact-item">
          <img src="/assets/linkedin-icon.png" alt="LinkedIn">
          <a href="https://linkedin.com/in/radindinsara">linkedin.com/in/radindinsara</a>
        </div>
        <div class="contact-item">
          <img src="/assets/github-icon.png" alt="GitHub">
          <a href="https://github.com/radindinsara">github.com/radindinsara</a>
        </div>
      </div>
    </div>
  </div>
